# Generated by Django 3.1.4 on 2021-01-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meats',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
