# Generated by Django 3.1.4 on 2021-01-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_meats_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabeldailydate',
            new_name='Tabledailydate',
        ),
    ]
