# Generated by Django 3.1.4 on 2021-01-11 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210109_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.meats')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.orders')),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='meats',
            field=models.ManyToManyField(through='customer.OrderMeat', to='customer.Meats'),
        ),
    ]
