# Generated by Django 3.1.4 on 2021-01-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210112_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='meats',
            field=models.ManyToManyField(to='customer.Meats'),
        ),
        migrations.DeleteModel(
            name='OrderMeat',
        ),
    ]
