# Generated by Django 3.1.4 on 2020-12-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='serve_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabeldailydate',
            name='table_close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
