# Generated by Django 3.1.4 on 2020-12-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201223_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meat',
        ),
        migrations.AddField(
            model_name='order',
            name='meats',
            field=models.ManyToManyField(to='customer.meat'),
        ),
    ]
